SELECT * 
FROM dbo.flights


DELETE FROM dbo.flights 
where SCHEDULED_TIME =' ' OR SCHEDULED_TIME IS NULL;

DELETE FROM dbo.flights
where ElAPSED_TIME = ' ' OR ELAPSED_TIME IS NULL 


--WHICH AIRLINE HAD THE HIGHEST NUMBER OF DELAYS

SELECT AIRLINE,SCHEDULED_TIME,ELAPSED_TIME,((cast(ELAPSED_TIME as float) -cast(SCHEDULED_TIME as float))/ cast(SCHEDULED_TIME as float))*100 AS DELAYED_TIMEPERCENTAGE
FROM dbo.flights
group by AIRLINE,SCHEDULED_TIME,ELAPSED_TIME
order by DELAYED_TIMEPERCENTAGE desc


WITH DELAYED_TABLE AS
(
SELECT AIRLINE,SCHEDULED_TIME,ELAPSED_TIME,((cast(ELAPSED_TIME as float) -cast(SCHEDULED_TIME as float))/ cast(SCHEDULED_TIME as float))*100 AS DELAYED_TIMEPERCENTAGE
FROM dbo.flights
)
SELECT AIRLINE , SUM(DELAYED_TIMEPERCENTAGE) AS TOTALDELAYPERCENT
FROM DELAYED_TABLE
WHERE DELAYED_TIMEPERCENTAGE > 0
GROUP BY AIRLINE
ORDER BY SUM(DELAYED_TIMEPERCENTAGE)desc


--WHAT IS THE AVERAGE DELAY TIME FOR EACH AIRLINE
SELECT AIRLINE,SCHEDULED_TIME,ELAPSED_TIME,cast(ELAPSED_TIME as float) -cast(SCHEDULED_TIME as float) AS DELAYED_TIME
FROM dbo.flights
group by AIRLINE,SCHEDULED_TIME,ELAPSED_TIME
order by DELAYED_TIME desc


WITH AVERAGEDELAYED_TABLE AS
(
SELECT AIRLINE,SCHEDULED_TIME,ELAPSED_TIME,cast(ELAPSED_TIME as float) -cast(SCHEDULED_TIME as float) AS DELAYED_TIME
FROM dbo.flights
)
SELECT AIRLINE , AVG(DELAYED_TIME) AS TOTALDELAYPERCENT
FROM AVERAGEDELAYED_TABLE
WHERE DELAYED_TIME > 0
GROUP BY AIRLINE
ORDER BY AVG(DELAYED_TIME)desc

--WHICH AIRPORTS HAVE THE MOST DELAYED FLIGHTS
SELECT * FROM dbo.airports$

select * from dbo.airlines$

select * from dbo.flights

SELECT ORIGIN_AIRPORT,SCHEDULED_TIME,ELAPSED_TIME,cast(ELAPSED_TIME as float) -cast(SCHEDULED_TIME as float) AS DELAYED_TIME_AT_AIRPORT
FROM dbo.flights
group by ORIGIN_AIRPORT,SCHEDULED_TIME,ELAPSED_TIME
order by DELAYED_TIME_AT_AIRPORT desc

WITH DELAYED_AIRPORTS AS
(
SELECT ORIGIN_AIRPORT,SCHEDULED_TIME,ELAPSED_TIME,cast(ELAPSED_TIME as float) -cast(SCHEDULED_TIME as float) AS DELAYED_TIME_AT_AIRPORT
FROM dbo.flights
)
SELECT ORIGIN_AIRPORT , SUM(DELAYED_TIME_AT_AIRPORT) AS TOTALDELAYAIRPORTS
FROM DELAYED_AIRPORTS
WHERE DELAYED_TIME_AT_AIRPORT > 0
GROUP BY ORIGIN_AIRPORT
ORDER BY SUM(DELAYED_TIME_AT_AIRPORT)desc

--WHICH DAYS OF THE WEEK HAS THE MOST DELAYED FLIGHTS
SELECT * FROM dbo.flights

SELECT DAY_OF_WEEK,SCHEDULED_TIME,ELAPSED_TIME,cast(ELAPSED_TIME as float) -cast(SCHEDULED_TIME as float) AS DELAYED_TIME_PER_DAY
FROM dbo.flights
group by DAY_OF_WEEK,SCHEDULED_TIME,ELAPSED_TIME
order by DELAYED_TIME_PER_DAY desc

WITH MOST_DELAYED_DAYS AS
(
SELECT DAY_OF_WEEK,SCHEDULED_TIME,ELAPSED_TIME,cast(ELAPSED_TIME as float) -cast(SCHEDULED_TIME as float) AS DELAYED_TIME_PER_DAY
FROM dbo.flights
)
SELECT DAY_OF_WEEK , SUM(DELAYED_TIME_PER_DAY) AS TOTALDELAYDAYS
FROM MOST_DELAYED_DAYS
WHERE DELAYED_TIME_PER_DAY> 0
GROUP BY DAY_OF_WEEK
ORDER BY SUM(DELAYED_TIME_PER_DAY)desc